&".\ProtoGen.exe" --proto_path="." --include_imports -output_directory="..\Protocols"  "virtuos\common.proto"
&".\ProtoGen.exe" --proto_path="." --include_imports -output_directory="..\Protocols"  "virtuos\request.proto"
&".\ProtoGen.exe" --proto_path="." --include_imports -output_directory="..\Protocols"  "virtuos\game.proto"
&".\ProtoGen.exe" --proto_path="." --include_imports -output_directory="..\Protocols"  "virtuos\push.proto"
&".\ProtoGen.exe" --proto_path="." --include_imports -output_directory="..\Protocols"  "virtuos\async.proto"
